{'Cardiff University': 'https://ror.org/03kk7td41',
 'Durham University': 'https://ror.org/01v29qb04',
 'Imperial College London': 'https://ror.org/041kmwe10',
 "King's College London": 'https://ror.org/0220mzb33',
 'Newcastle University': 'https://ror.org/01kj2bm70',
 'Queen Mary University of London': 'https://ror.org/026zzn846',
 "Queen's University Belfast": 'https://ror.org/00hswnk62',
 'University College London': 'https://ror.org/02jx3x895',
 'University of Aberdeen': 'https://ror.org/016476m91',
 'University of Birmingham': 'https://ror.org/03angcq70',
 'University of Bristol': 'https://ror.org/0524sp257',
 'University of Cambridge': 'https://ror.org/013meh722',
 'University of Edinburgh': 'https://ror.org/01nrxwf90',
 'University of Exeter': 'https://ror.org/03yghzc09',
 'University of Glasgow': 'https://ror.org/00vtgdb53',
 'University of Leeds': 'https://ror.org/024mrxd33',
 'University of Leicester': 'https://ror.org/04h699437',
 'University of Liverpool': 'https://ror.org/04xs57h96',
 'University of London': 'https://ror.org/04cw6st05',
 'University of Manchester': 'https://ror.org/027m9bs27',
 'University of Nottingham': 'https://ror.org/01ee9ar58',
 'University of Oxford': 'https://ror.org/052gg0110',
 'University of Sheffield': 'https://ror.org/05krs5044',
 'University of Southampton': 'https://ror.org/01ryk1543',
 'University of Warwick': 'https://ror.org/01a77tt86'}
