{'Australian National University': 'https://ror.org/019wvm592',
 'Commonwealth Scientific and Industrial Research Organisation': 'https://ror.org/03qn8fb07',
 'Curtin University': 'https://ror.org/02n415q13',
 'Deakin University': 'https://ror.org/02czsnj07',
 'Flinders University': 'https://ror.org/01kpzv902',
 'Griffith University': 'https://ror.org/02sc3r913',
 'James Cook University': 'https://ror.org/04gsp2c11',
 'La Trobe University': 'https://ror.org/01rxfrp27',
 'Macquarie University': 'https://ror.org/01sf06y89',
 'Monash University': 'https://ror.org/02bfwt286',
 'Queensland University of Technology': 'https://ror.org/03pnv4752',
 'RMIT University': 'https://ror.org/04ttjf776',
 'Swinburne University of Technology': 'https://ror.org/031rekg67',
 'UNSW Sydney': 'https://ror.org/03r8z3t63',
 'University of Adelaide': 'https://ror.org/00892tw58',
 'University of Melbourne': 'https://ror.org/01ej9dk98',
 'University of Newcastle Australia': 'https://ror.org/00eae9z71',
 'University of Queensland': 'https://ror.org/00rqy9422',
 'University of South Australia': 'https://ror.org/01p93h210',
 'University of Sydney': 'https://ror.org/0384j8v12',
 'University of Tasmania': 'https://ror.org/01nfmeh72',
 'University of Technology Sydney': 'https://ror.org/03f0f6041',
 'University of Western Australia': 'https://ror.org/047272k79',
 'University of Wollongong': 'https://ror.org/00jtmb277',
 'Western Sydney University': 'https://ror.org/03t52dk35'}
